#!/bin/bash
### BEGIN INIT INFO
# Provides:          ipt
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: manipulate iptables through ipt
### END INIT INFO


IPT="/usr/bin/ipt"

usage() {
  echo "Usage: $0 {start|stop|restart|reload|status|config}";
}

start() {
  iptables-restore < /etc/iptables.rules
  if [ "$?" = "0" ]; then
    echo "iptables configured with ipt rules";
  fi;
}

stop() {
  iptables -F
  if [ "$?" = "0" ]; then
    echo "iptables rules flushed";
  fi;
}

case "$1" in
  "start")     start ;;
  "stop")      stop ;;
  "restart")   stop; start ;;
  "reload")    $IPT -i; ;;
  "status")    iptables -L ;;
  "config")    cat /etc/iptables.rules ;;
  *)           usage ;;
esac;
