#!/bin/bash

source /etc/iprules.conf;

# Create the rules file if none exists
if ! [ -f "$RULES_FILE" ]; then
  ipt -g;
fi;

# Copy over the policy file if none exists
if ! [ -f "$POLICY_FILE" ]; then
  echo "Installing default accept policy file ($POLICY_FILE)"
  cp "/usr/share/iprules/contrib/policy.rules" "$POLICY_FILE";
fi;

copy_rules() {
  cp /usr/share/iprules/rules/* "$A_PATH" $1;
}

# Copy over the rules if wanted
if [ "$(ls $A_PATH|wc -l)" = "0" ]; then
  copy_rules;
else
  echo -n "Do you want to install default rules? [y]es,[N]o,[o]verwrite: ";
  read ANS;
  case "$ANS" in
    "o")  copy_rules ;;     # overwrite
    "O")  copy_rules ;;     # overwrite
    "y")  copy_rules -n ;;  # don't overwrite
    "Y")  copy_rules -n ;;  # don't overwrite
    *)  echo "You can find default rules in /usr/share/iprules/rules/" ;;
  esac;
fi;

# Protect everything for root only access
chown root:root /etc/iptables* /etc/iprules.conf -R
chmod o-rwx /etc/iptables* /etc/iprules.conf -R
